TrajectoryPlannerROS:
  max_vel_x: 0.08
  min_vel_x: 0.04
  max_vel_theta: 0.3
  min_vel_theta: -0.3
  min_in_place_vel_theta: 0.4

  acc_lim_theta: 1.0
  acc_lim_x: 1.0
  acc_lim_y: 0.0
  
  xy_goal_tolerance: 0.1
  yaw_goal_tolerance: 0.1
  latch_xy_goal_tolerance: false
  
  holonomic_robot: false
