local_costmap:
  global_frame: odom
  robot_base_frame: car_base
  update_frequency: 1.0
  publish_frequency: 2.0
  static_map: true
  rolling_window: true
  width: 3.0
  height: 3.0
  resolution: 0.1
  transform_tolerance: 3.0
