joints: ['arm_shoulder_pan_joint', 'arm_shoulder_lift_joint', 'arm_elbow_flex_joint', 'arm_wrist_flex_joint', 'gripper_link_joint']

arm_shoulder_pan_joint:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: arm_shoulder_pan_joint
    joint_speed: 2
    motor:
        id: 1
        init: 512
        min: 0
        max: 1023

arm_shoulder_lift_joint:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: arm_shoulder_lift_joint
    joint_speed: 2
    motor:
        id: 2
        init: 512
        min: 0
        max: 1023

arm_elbow_flex_joint:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: arm_elbow_flex_joint
    joint_speed: 2
    motor:
        id: 3
        init: 512
        min: 0
        max: 1023

arm_wrist_flex_joint:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: arm_wrist_flex_joint
    joint_speed: 2
    motor:
        id: 4
        init: 512
        min: 0
        max: 1023

gripper_joint:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: gripper_joint
    joint_speed: 1
    motor:
        id: 5
        init: 512
        min: 0
        max: 1023

