frequency: 8.0
two_d_mode: true
publish_tf: true
map_frame: map
odom_frame: odom
base_link_frame: car_base
world_frame: odom
odom0: wheel_odom
odom0_config: [true, true, false,
               false, false, true,
               false,  false, false,
               false, false, false,
               false, false, false]
odom0_queue_size: 10
odom0_differential: false
odom0_relative: true
odom0_pose_rejection_threshold: 5
odom0_twist_rejection_threshold: 1

pose0: car_pose_from_tag
pose0_config: [true, true, false,
               false, false, true,
               false, false, false,
               false, false, false,
               false, false, false]
pose0_differential: false
pose0_relative: false
pose0_pose_rejection_threshold: 5
pose0_twist_rejection_threshold: 1

use_control: false
