controller_list:
  - name: arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - arm_shoulder_pan_joint
      - arm_shoulder_lift_joint
      - arm_elbow_flex_joint
      - arm_wrist_flex_joint

  - name: gripper_controller
    action_ns: gripper_action
    type: FollowJointTrajectory
    default: true
    joints:
      - gripper_joint